version: '3.8'

services:
  traefik:
    image: "traefik:v2.5"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=info@cultchain.foundation"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.api.rule=Host(`monitor.cultchain.com`)"
      - "traefik.http.routers.api.service=api@internal"

  web:
    build: .
    command: '/bin/bash -c "chmod +x /usr/src/app/docker-entrypoint.sh && /usr/src/app/docker-entrypoint.sh"'
    volumes:
      - .:/usr/src/app/
    labels:
      - "traefik.http.routers.web-secure.entrypoints=web-secure"
        - "traefik.http.routers.web-secure.rule=Host(`cultchain.com`)"
        - "traefik.http.routers.web-secure.tls.certresolver=letsencrypt"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=cultchain_db

  redis:
    image: "redis:latest"

  celery_worker:
    build: .
    command: celery -A cultchian_backend worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: celery -A cultchian_backend beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
