[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[log]
  level = "ERROR"

[providers.docker]
  exposedByDefault = false
