# Generated by Django 4.2.6 on 2023-10-17 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('CharityEvent', 'CharityEvent'), ('Fundraising', 'Fundraising'), ('RandomizedCommittee', 'RandomizedCommittee'), ('Validator', 'Validator'), ('CultChainNFT', 'CultChainNFT'), ('CultChainToken', 'CultChainToken')], max_length=20)),
                ('contract_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=42)),
                ('abi', models.JSONField()),
                ('owner_address', models.CharField(max_length=42)),
                ('deployed_at_block', models.IntegerField(default=0)),
                ('last_processed_event_block', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('chainId', models.IntegerField(default=1)),
                ('rpc_endpoint', models.URLField()),
                ('explorer', models.URLField()),
                ('is_testnet', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='contract_parser.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract_parser.network'),
        ),
    ]
