# Generated by Django 4.2.6 on 2023-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Personal', 'Personal'), ('Corporate', 'Corporate')], default='Personal', max_length=10)),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_donor', models.BooleanField(default=False)),
                ('is_validator', models.BooleanField(default=False)),
                ('is_creator', models.BooleanField(default=False)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
