# Generated by Django 4.2.6 on 2023-10-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='committee_type_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='committee',
            name='milestone_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
