# Generated by Django 4.2.6 on 2023-10-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together={('donor', 'amount', 'event', 'timestamp', 'message')},
        ),
    ]
